In [39]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [40]:
df = pd.read_csv("/Users/nilesh/Downloads/Data Science/Test_Dataset/diabetes.csv")

In [41]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [42]:
arr = df.values

In [43]:
arr

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [44]:
#NUMPY will help us for data cleansing

In [45]:
X = arr[:,0:8]

In [46]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [47]:
Y = arr[:,8]

In [48]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [49]:
test = SelectKBest(score_func=chi2, k = 4)
fit = test.fit(X,Y)

In [50]:
np.set_printoptions(precision=3)
print(fit.scores_)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [51]:
features = fit.transform(X)

In [52]:
features

array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

In [53]:
print(features[0:5,:])

[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]


In [54]:
from sklearn.feature_selection import RFE

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
model = LinearRegression()

In [57]:
rfe = RFE(model, 4)

In [58]:
fit = rfe.fit(X, Y)

In [59]:
print("Num of feature: %s" % (fit.n_features_))
print("Selected feature: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num of feature: 4
Selected feature: [ True  True False False False  True  True False]
Feature Ranking: [1 1 3 5 4 1 1 2]


In [60]:
DF = pd.DataFrame({"Area":[2600, 3300, 2500, 3000, 4500], 
                          "Bedroom":[3, 4, 3, None, 5],
                  "Age":[5, 10, 1, 3, 6], 
                          "Price": [550000, 610000, 590000, 720000, 
                                   780000]})

In [61]:
DF

Area  Bedroom  Age   Price
0  2600      3.0    5  550000
1  3300      4.0   10  610000
2  2500      3.0    1  590000
3  3000      NaN    3  720000
4  4500      5.0    6  780000

In [62]:
DF.Bedroom.median()

3.5

In [63]:
import math

In [64]:
median_bedroom = math.floor(DF.Bedroom.median())

In [65]:
median_bedroom

3

In [66]:
DF['Bedroom'] = DF['Bedroom'].fillna(median_bedroom)
DF

Area  Bedroom  Age   Price
0  2600      3.0    5  550000
1  3300      4.0   10  610000
2  2500      3.0    1  590000
3  3000      3.0    3  720000
4  4500      5.0    6  780000

In [67]:
reg = LinearRegression()

In [68]:
reg.fit(DF[['Area', 'Bedroom', 'Age']], DF.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [69]:
reg.coef_

array([    278.349, -159744.862,   -5294.118])

In [70]:
reg.intercept_

366403.2600992207

In [71]:
reg.predict([[3500, 4, 7]])

array([664585.4])

In [72]:
278.349*3500-159744.862*4-5294.118*7+366403.2600992207

664586.4860992207

In [73]:
from sklearn import cross_validation

In [74]:
from sklearn.cross_validation import train_test_split

In [75]:
data_set = pd.read_csv("/Users/nilesh/Downloads/diabetes.csv")

FileNotFoundError: File b'/Users/nilesh/Downloads/diabetes.csv' does not exist

In [ ]:
Y = data_set['Outcome']


In [ ]:
X = data_set.drop('Outcome', axis=1)

In [ ]:
X

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.25, 
                                                   random_state=20)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)

In [ ]:
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
cla = LinearRegression()

In [ ]:
cla.fit(X_train, y_train)

In [ ]:
y_pred = cla.predict(X_test)

In [ ]:
y_pred

In [ ]:
data_set.describe()

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm1 = confusion_matrix(y_test,y_pred.round())

In [ ]:
print(cm1)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred.round())

accuracy_score(y_test,y_pred.round())*100

In [ ]:
7//2

In [76]:
url = 'https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/data.csv'
tk = pd.read_csv(url)

In [77]:
tk.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

      ...       texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0     ...               17.33           184.60      2019.0            0.1622   
1     ...               23.41           158.80      1956.0            0.1238   
2     ...               25.53           152.50      1709.0            0.1444   
3     ...               26.50            98.87       567.7            0.2098   
4     ...               16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]