In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
DF = pd.DataFrame({"Area":[2600, 3300, 2500, 3000, 4500], 
                          "Bedroom":[3, 4, 3, None, 5],
                  "Age":[5, 10, 1, 3, 6], 
                          "Price": [550000, 610000, 590000, 720000, 
                                   780000]})

In [3]:
DF

Area  Bedroom  Age   Price
0  2600      3.0    5  550000
1  3300      4.0   10  610000
2  2500      3.0    1  590000
3  3000      NaN    3  720000
4  4500      5.0    6  780000

In [4]:
DF.Bedroom.median()

3.5

In [5]:
import math

In [6]:
median_bedroom = math.floor(DF.Bedroom.median())

In [7]:
median_bedroom

3

In [8]:
DF['Bedroom'] = DF['Bedroom'].fillna(median_bedroom)
DF

Area  Bedroom  Age   Price
0  2600      3.0    5  550000
1  3300      4.0   10  610000
2  2500      3.0    1  590000
3  3000      3.0    3  720000
4  4500      5.0    6  780000

In [9]:
reg = LinearRegression()

In [10]:
reg.fit(DF[['Area', 'Bedroom', 'Age']], DF.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
reg.coef_

array([    278.34868887, -159744.86180014,   -5294.11764706])

In [12]:
reg.intercept_

366403.2600992207

In [13]:
reg.predict([[3500, 4, 7]])

array([664585.40042523])

In [14]:
import pickle

In [16]:
#with open('model_pickle','wb') as f:
 #   pickle.dump(reg,f)

In [17]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [27]:
mp.predict([[3500, 4, 7]])

array([664585.40042523])

In [23]:
from sklearn.externals import joblib

In [24]:
#joblib.dump(reg, 'model_joblib')

['model_joblib']

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.predict([[3500, 4, 7]])

array([664585.40042523])

In [40]:
Xtest = pd.read_csv("property_pune.csv")

In [35]:
mj.predict(Xtest)

array([392884.47909284, 668515.23742027, 443866.05244507])